export enum LoginTypes {
   SIGN_IN_REQUEST = 'auth/SIGN_IN_REQUEST',
   SIGN_IN_SUCCESS = 'auth/SIGN_IN_SUCCESS',
   SIGN_IN_ERROR = 'auth/SIGN_IN_ERROR',
   SIGN_OUT_REQUEST = 'auth/SIGN_OUT_REQUEST',
}
